"""Squashed baseline: migrations 0001-0061 compressed into single file.

This migration replaces the original 61 incremental migrations (0001-0061)
with a single baseline that creates the complete schema as of revision 0061.
Incremental migrations 0062-0068 (multi-tenant department_id upgrade) are preserved.

Schema contents:
- PostgreSQL extensions: citext, pgcrypto, vector
- Trigger function: raise_immutable_violation()
- 40 tables with primary keys, unique constraints, indexes, foreign keys
- Row Level Security: ENABLE + FORCE on tenant tables, tenant_isolation policies
- Immutable table triggers (audit_event, component_version, evidence_set_version, flow_definition_version)
- Database roles: irip_migrate, irip_runtime, irip_audit_writer, irip_app
- Role grants and default privileges

Generated by pg_dump --schema-only from a fresh database at revision 0061,
supplemented with manually authored role/grant DDL not captured by pg_dump.

Revision ID: 0001
Revises:
Create Date: 2026-09-01
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---- Table name constants for role/grant management ----

#: All business tables that exist at revision 0061.
_ALL_TABLES: list[str] = ['ai_config', 'ai_conversation', 'ai_message', 'ai_showcase_item', 'ai_tool', 'app_user', 'app_user_department', 'artifact', 'artifact_blob', 'audit_event', 'backup_record', 'component', 'component_version', 'conversation_participant', 'department', 'derivation_run', 'equipment', 'evidence_set', 'evidence_set_version', 'fact', 'fact_data_index', 'flow_definition', 'flow_definition_version', 'flow_node_execution', 'flow_run', 'industrial_object', 'job', 'model', 'model_version', 'object_type_dict', 'outbox_event', 'parameter', 'parameter_candidate', 'parameter_version', 'provenance_edge', 'refresh_session', 'role', 'secret', 'transformation_recipe', 'transformation_recipe_version']

#: Tables where irip_app has CRUD grants (from migration 0005, minus later-dropped tables).
_IRIP_APP_TABLES: list[str] = ['ai_config', 'ai_conversation', 'ai_message', 'ai_showcase_item', 'ai_tool', 'app_user', 'app_user_department', 'artifact', 'artifact_blob', 'audit_event', 'component', 'component_version', 'conversation_participant', 'department', 'derivation_run', 'equipment', 'evidence_set', 'evidence_set_version', 'fact', 'flow_definition', 'flow_definition_version', 'flow_node_execution', 'flow_run', 'industrial_object', 'job', 'model', 'model_version', 'object_type_dict', 'outbox_event', 'parameter', 'parameter_candidate', 'parameter_version', 'provenance_edge', 'refresh_session', 'role', 'secret', 'transformation_recipe', 'transformation_recipe_version']

#: Immutable tables -- runtime role gets only SELECT + INSERT.
_IMMUTABLE_TABLES: list[str] = ['component_version', 'flow_definition_version', 'audit_event', 'evidence_set_version']

#: Audit event table -- special grant handling.
_AUDIT_TABLE: str = "audit_event"


# ---- Raw schema SQL from pg_dump (extensions, tables, constraints, indexes, triggers, RLS) ----

_SCHEMA_SQL = r"""SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';
CREATE FUNCTION public.raise_immutable_violation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            RAISE EXCEPTION 'Table % is immutable: UPDATE/DELETE not allowed (F-03)',
                TG_TABLE_NAME;
        END;
        $$;
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.ai_config (
    id integer DEFAULT 1 NOT NULL,
    base_url text DEFAULT ''::text NOT NULL,
    api_key text DEFAULT ''::text NOT NULL,
    model_name text DEFAULT ''::text NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    thinking_enabled boolean DEFAULT false NOT NULL,
    assistant_model_name text
);
CREATE TABLE public.ai_conversation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    user_id uuid NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    provider_mode text DEFAULT 'offline'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    pinned boolean DEFAULT false NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    system_context text
);
ALTER TABLE ONLY public.ai_conversation FORCE ROW LEVEL SECURITY;
CREATE TABLE public.ai_message (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    role text NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    tool_calls_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    citations_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    uncertainty text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    mentions jsonb DEFAULT '[]'::jsonb NOT NULL,
    sender_user_id uuid,
    sender_display_name text,
    sender_avatar_url text
);
CREATE TABLE public.ai_showcase_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    block_type character varying(32) NOT NULL,
    title character varying(200) DEFAULT ''::character varying NOT NULL,
    content_snapshot text NOT NULL,
    source_message_id uuid NOT NULL,
    source_block_index integer DEFAULT 0 NOT NULL,
    data_source jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.ai_tool (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    display_name text NOT NULL,
    description text NOT NULL,
    required_permission text NOT NULL,
    parameters_schema jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    category text DEFAULT 'ai_tool'::text NOT NULL
);

CREATE TABLE public.app_user (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid,
    email public.citext NOT NULL,
    display_name text NOT NULL,
    password_hash text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    roles jsonb DEFAULT '[]'::jsonb NOT NULL,
    department_id uuid,
    token_version integer DEFAULT 0 NOT NULL,
    avatar_url text
);
ALTER TABLE ONLY public.app_user FORCE ROW LEVEL SECURITY;
CREATE TABLE public.app_user_department (
    user_id uuid NOT NULL,
    department_id uuid NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.artifact (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    sha256 text NOT NULL,
    filename text NOT NULL,
    media_type text NOT NULL,
    size_bytes bigint NOT NULL,
    uploaded_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.artifact FORCE ROW LEVEL SECURITY;
CREATE TABLE public.artifact_blob (
    sha256 text NOT NULL,
    object_key text NOT NULL,
    size_bytes bigint NOT NULL,
    media_type text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.audit_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    actor_user_id uuid,
    organization_id uuid NOT NULL,
    action text NOT NULL,
    resource_type text,
    resource_id uuid,
    payload jsonb,
    ip text,
    user_agent text
);
ALTER TABLE ONLY public.audit_event FORCE ROW LEVEL SECURITY;
CREATE TABLE public.backup_record (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid,
    backup_type character varying(20) NOT NULL,
    name character varying(100),
    description character varying(500),
    backup_date date,
    file_path text NOT NULL,
    file_size bigint,
    sha256 character varying(64),
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    migration_version character varying(100),
    application_version character varying(50),
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    expires_at timestamp with time zone,
    error_message text,
    organization_id uuid NOT NULL,
    backup_timestamp timestamp with time zone,
    wal_start_lsn character varying(64),
    wal_end_lsn character varying(64),
    recovery_target_time timestamp with time zone,
    backup_method character varying(20) DEFAULT 'pitr'::character varying NOT NULL,
    CONSTRAINT chk_backup_record_status CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'succeeded'::character varying, 'failed'::character varying])::text[]))),
    CONSTRAINT chk_backup_record_type CHECK (((backup_type)::text = ANY ((ARRAY['daily'::character varying, 'milestone'::character varying, 'pre_restore'::character varying])::text[])))
);
ALTER TABLE ONLY public.backup_record FORCE ROW LEVEL SECURITY;
CREATE TABLE public.component (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    active_version_id uuid
);
ALTER TABLE ONLY public.component FORCE ROW LEVEL SECURITY;
CREATE TABLE public.component_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    component_id uuid NOT NULL,
    version text NOT NULL,
    manifest_yaml text NOT NULL,
    manifest_sha256 text NOT NULL,
    runtime text NOT NULL,
    port_schemas jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'published'::text NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    experimental_object_code text,
    equipment_id text
);
CREATE TABLE public.conversation_participant (
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role character varying(20) DEFAULT 'member'::character varying NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.department (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    description text,
    status text DEFAULT 'active'::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    parent_id uuid
);
ALTER TABLE ONLY public.department FORCE ROW LEVEL SECURITY;
CREATE TABLE public.derivation_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    evidence_set_version_id uuid NOT NULL,
    recipe_version_id uuid NOT NULL,
    job_id uuid,
    status text DEFAULT 'pending'::text NOT NULL,
    output_digest text,
    outputs jsonb,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.derivation_run FORCE ROW LEVEL SECURITY;
CREATE TABLE public.equipment (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    description text,
    department_id uuid NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    visible_departments jsonb DEFAULT '[]'::jsonb NOT NULL
);
ALTER TABLE ONLY public.equipment FORCE ROW LEVEL SECURITY;
CREATE TABLE public.evidence_set (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    name text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid
);
ALTER TABLE ONLY public.evidence_set FORCE ROW LEVEL SECURITY;
CREATE TABLE public.evidence_set_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    evidence_set_id uuid NOT NULL,
    version integer NOT NULL,
    status text DEFAULT 'frozen'::text NOT NULL,
    members jsonb NOT NULL,
    member_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    frozen_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.fact (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    fact_type text NOT NULL,
    object_id uuid NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    idempotency_key text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    subject_id text DEFAULT ''::text NOT NULL,
    flow_run_id uuid,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    task_code text,
    task_name text,
    department_name text,
    operator text,
    run_operator text,
    equipment_name text,
    source_artifact_id uuid,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, ((COALESCE(subject_id, ''::text) || ' '::text) || COALESCE(fact_type, ''::text)))) STORED
);
ALTER TABLE ONLY public.fact FORCE ROW LEVEL SECURITY;
CREATE TABLE public.fact_data_index (
    id uuid NOT NULL,
    fact_id uuid NOT NULL,
    row_index integer NOT NULL,
    key text NOT NULL,
    value_text text,
    value_number double precision
);
CREATE TABLE public.flow_definition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    department_id uuid,
    project_name text,
    operator text,
    experimental_object_code text
);
ALTER TABLE ONLY public.flow_definition FORCE ROW LEVEL SECURITY;
CREATE TABLE public.flow_definition_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    flow_definition_id uuid NOT NULL,
    version integer NOT NULL,
    nodes_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    edges_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    random_seed integer DEFAULT 0 NOT NULL,
    digest text NOT NULL,
    status text DEFAULT 'published'::text NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.flow_node_execution (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    flow_run_id uuid NOT NULL,
    node_id text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    input_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    output_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    diagnostics jsonb,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    duration_ms integer
);
CREATE TABLE public.flow_run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    flow_version_id uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    job_id uuid,
    input_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    output_digest text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.flow_run FORCE ROW LEVEL SECURITY;
CREATE TABLE public.industrial_object (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    object_type text NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    description text,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    equipment_id uuid,
    department_id uuid,
    visible_departments jsonb DEFAULT '[]'::jsonb NOT NULL
);
ALTER TABLE ONLY public.industrial_object FORCE ROW LEVEL SECURITY;
CREATE TABLE public.job (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    kind text NOT NULL,
    status text NOT NULL,
    payload jsonb,
    idempotency_key text NOT NULL,
    attempt integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    run_after timestamp with time zone,
    lease_owner text,
    lease_expires_at timestamp with time zone,
    result jsonb,
    last_error jsonb,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL
);
ALTER TABLE ONLY public.job FORCE ROW LEVEL SECURITY;
CREATE TABLE public.model (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    current_version_id uuid,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.model FORCE ROW LEVEL SECURITY;
CREATE TABLE public.model_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    model_id uuid NOT NULL,
    version integer NOT NULL,
    contract_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    model_artifact_id uuid,
    metrics_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    applicability_domain_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    code_hash text,
    dependency_hash text,
    model_hash text,
    status text DEFAULT 'draft'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone
);
CREATE TABLE public.object_type_dict (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    description text,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.outbox_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type text NOT NULL,
    payload jsonb,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    delivered_at timestamp with time zone
);
CREATE TABLE public.parameter (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    variable_code text NOT NULL,
    object_id uuid NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid
);
ALTER TABLE ONLY public.parameter FORCE ROW LEVEL SECURITY;
CREATE TABLE public.parameter_candidate (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    parameter_id uuid NOT NULL,
    derivation_run_id uuid NOT NULL,
    value text NOT NULL,
    unit text,
    confidence text,
    confidence_interval jsonb,
    conditions jsonb,
    status text DEFAULT 'pending_review'::text NOT NULL,
    submitted_by uuid NOT NULL,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    review_decision text,
    review_comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.parameter_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    parameter_id uuid NOT NULL,
    version integer NOT NULL,
    value text NOT NULL,
    unit text,
    confidence text,
    confidence_interval jsonb,
    conditions jsonb,
    derivation_run_id uuid NOT NULL,
    status text DEFAULT 'published'::text NOT NULL,
    published_at timestamp with time zone DEFAULT now() NOT NULL,
    published_by uuid NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.provenance_edge (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    derivation_run_id uuid NOT NULL,
    source_type text NOT NULL,
    source_id uuid NOT NULL,
    target_type text NOT NULL,
    target_id uuid NOT NULL,
    edge_type text NOT NULL,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.provenance_edge FORCE ROW LEVEL SECURITY;
CREATE TABLE public.refresh_session (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    family_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_digest text NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by uuid,
    created_ip text,
    user_agent text
);
CREATE TABLE public.role (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    permissions jsonb DEFAULT '[]'::jsonb NOT NULL
);
CREATE TABLE public.secret (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    kind text NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.secret FORCE ROW LEVEL SECURITY;
CREATE TABLE public.transformation_recipe (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    code text NOT NULL,
    display_name text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    lock_version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.transformation_recipe FORCE ROW LEVEL SECURITY;
CREATE TABLE public.transformation_recipe_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    recipe_id uuid NOT NULL,
    version integer NOT NULL,
    component_name text NOT NULL,
    component_version text NOT NULL,
    parameters jsonb NOT NULL,
    random_seed integer NOT NULL,
    output_definitions jsonb NOT NULL,
    status text DEFAULT 'published'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.ai_config
    ADD CONSTRAINT ai_config_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ai_conversation
    ADD CONSTRAINT ai_conversation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ai_message
    ADD CONSTRAINT ai_message_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ai_showcase_item
    ADD CONSTRAINT ai_showcase_item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ai_tool
    ADD CONSTRAINT ai_tool_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.artifact_blob
    ADD CONSTRAINT artifact_blob_pkey PRIMARY KEY (sha256);
ALTER TABLE ONLY public.artifact
    ADD CONSTRAINT artifact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_event
    ADD CONSTRAINT audit_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.component
    ADD CONSTRAINT component_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.component_version
    ADD CONSTRAINT component_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.derivation_run
    ADD CONSTRAINT derivation_run_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.evidence_set
    ADD CONSTRAINT evidence_set_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.evidence_set_version
    ADD CONSTRAINT evidence_set_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fact_data_index
    ADD CONSTRAINT fact_data_index_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flow_definition
    ADD CONSTRAINT flow_definition_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flow_definition_version
    ADD CONSTRAINT flow_definition_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flow_node_execution
    ADD CONSTRAINT flow_node_execution_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flow_run
    ADD CONSTRAINT flow_run_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.industrial_object
    ADD CONSTRAINT industrial_object_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.model
    ADD CONSTRAINT model_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.model_version
    ADD CONSTRAINT model_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.object_type_dict
    ADD CONSTRAINT object_type_dict_code_key UNIQUE (code);
ALTER TABLE ONLY public.object_type_dict
    ADD CONSTRAINT object_type_dict_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.outbox_event
    ADD CONSTRAINT outbox_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parameter_candidate
    ADD CONSTRAINT parameter_candidate_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parameter
    ADD CONSTRAINT parameter_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parameter_version
    ADD CONSTRAINT parameter_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT pk_conversation_participant PRIMARY KEY (conversation_id, user_id);
ALTER TABLE ONLY public.provenance_edge
    ADD CONSTRAINT provenance_edge_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_session
    ADD CONSTRAINT refresh_session_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.secret
    ADD CONSTRAINT secret_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transformation_recipe
    ADD CONSTRAINT transformation_recipe_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transformation_recipe_version
    ADD CONSTRAINT transformation_recipe_version_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ai_tool
    ADD CONSTRAINT uq_ai_tool_name UNIQUE (name);
ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uq_app_user_email UNIQUE (email);
ALTER TABLE ONLY public.artifact_blob
    ADD CONSTRAINT uq_artifact_blob_object_key UNIQUE (object_key);
ALTER TABLE ONLY public.component
    ADD CONSTRAINT uq_component_org_name UNIQUE (organization_id, name);
ALTER TABLE ONLY public.component_version
    ADD CONSTRAINT uq_component_version_comp_ver UNIQUE (component_id, version);
ALTER TABLE ONLY public.department
    ADD CONSTRAINT uq_department_org_code UNIQUE (organization_id, code);
ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT uq_equipment_org_code UNIQUE (organization_id, code);
ALTER TABLE ONLY public.evidence_set_version
    ADD CONSTRAINT uq_evidence_set_version_set_version UNIQUE (evidence_set_id, version);
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT uq_fact_org_idempotency UNIQUE (organization_id, idempotency_key);
ALTER TABLE ONLY public.flow_definition
    ADD CONSTRAINT uq_flow_definition_org_code UNIQUE (organization_id, code);
ALTER TABLE ONLY public.flow_definition_version
    ADD CONSTRAINT uq_flow_version_def_ver UNIQUE (flow_definition_id, version);
ALTER TABLE ONLY public.industrial_object
    ADD CONSTRAINT uq_industrial_object_org_type_code UNIQUE (organization_id, object_type, code);
ALTER TABLE ONLY public.job
    ADD CONSTRAINT uq_job_organization_idempotency_key UNIQUE (organization_id, idempotency_key);
ALTER TABLE ONLY public.model
    ADD CONSTRAINT uq_model_org_code UNIQUE (organization_id, code);
ALTER TABLE ONLY public.model_version
    ADD CONSTRAINT uq_model_version_model_ver UNIQUE (model_id, version);
ALTER TABLE ONLY public.parameter_candidate
    ADD CONSTRAINT uq_parameter_candidate_param_deriv UNIQUE (parameter_id, derivation_run_id);
ALTER TABLE ONLY public.parameter
    ADD CONSTRAINT uq_parameter_org_var_obj UNIQUE (organization_id, variable_code, object_id);
ALTER TABLE ONLY public.parameter_version
    ADD CONSTRAINT uq_parameter_version_param_version UNIQUE (parameter_id, version);
ALTER TABLE ONLY public.transformation_recipe_version
    ADD CONSTRAINT uq_recipe_version_recipe_version UNIQUE (recipe_id, version);
ALTER TABLE ONLY public.refresh_session
    ADD CONSTRAINT uq_refresh_session_token_digest UNIQUE (token_digest);
ALTER TABLE ONLY public.role
    ADD CONSTRAINT uq_role_code UNIQUE (code);
ALTER TABLE ONLY public.transformation_recipe
    ADD CONSTRAINT uq_transformation_recipe_org_code UNIQUE (organization_id, code);
ALTER TABLE ONLY public.app_user_department
    ADD CONSTRAINT uq_user_department UNIQUE (user_id, department_id);
CREATE INDEX idx_backup_record_date ON public.backup_record USING btree (backup_date);
CREATE INDEX idx_backup_record_expires ON public.backup_record USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX idx_backup_record_method ON public.backup_record USING btree (backup_method);
CREATE INDEX idx_backup_record_type ON public.backup_record USING btree (backup_type);
CREATE INDEX idx_conv_participant_user ON public.conversation_participant USING btree (user_id);
CREATE INDEX idx_showcase_conv_sort ON public.ai_showcase_item USING btree (conversation_id, sort_order);
CREATE INDEX ix_ai_conversation_org_user ON public.ai_conversation USING btree (organization_id, user_id);
CREATE INDEX ix_ai_conversation_pinned_archived ON public.ai_conversation USING btree (archived, pinned, updated_at);
CREATE INDEX ix_ai_conversation_user_id ON public.ai_conversation USING btree (user_id);
CREATE INDEX ix_ai_message_conversation_id ON public.ai_message USING btree (conversation_id);
CREATE INDEX ix_artifact_organization_id ON public.artifact USING btree (organization_id);
CREATE INDEX ix_artifact_sha256 ON public.artifact USING btree (sha256);
CREATE INDEX ix_artifact_uploaded_by ON public.artifact USING btree (uploaded_by);
CREATE INDEX ix_audit_event_actor_user_id ON public.audit_event USING btree (actor_user_id);
CREATE INDEX ix_audit_event_occurred_at ON public.audit_event USING btree (occurred_at);
CREATE INDEX ix_audit_event_organization_id ON public.audit_event USING btree (organization_id);
CREATE INDEX ix_component_active_version_id ON public.component USING btree (active_version_id);
CREATE INDEX ix_component_organization_id ON public.component USING btree (organization_id);
CREATE INDEX ix_component_version_component_id ON public.component_version USING btree (component_id);
CREATE INDEX ix_department_organization_id ON public.department USING btree (organization_id);
CREATE INDEX ix_department_parent_id ON public.department USING btree (parent_id);
CREATE INDEX ix_department_status ON public.department USING btree (status);
CREATE INDEX ix_derivation_run_evidence_set_version_id ON public.derivation_run USING btree (evidence_set_version_id);
CREATE INDEX ix_derivation_run_organization_id ON public.derivation_run USING btree (organization_id);
CREATE INDEX ix_derivation_run_recipe_version_id ON public.derivation_run USING btree (recipe_version_id);
CREATE INDEX ix_equipment_department_id ON public.equipment USING btree (department_id);
CREATE INDEX ix_equipment_organization_id ON public.equipment USING btree (organization_id);
CREATE INDEX ix_equipment_visible_departments ON public.equipment USING gin (visible_departments);
CREATE INDEX ix_evidence_set_organization_id ON public.evidence_set USING btree (organization_id);
CREATE INDEX ix_evidence_set_version_evidence_set_id ON public.evidence_set_version USING btree (evidence_set_id);
CREATE INDEX ix_fact_fact_type ON public.fact USING btree (fact_type);
CREATE INDEX ix_fact_object_id ON public.fact USING btree (object_id);
CREATE INDEX ix_fact_organization_id ON public.fact USING btree (organization_id);
CREATE INDEX ix_fact_search_vector ON public.fact USING gin (search_vector);
CREATE INDEX ix_flow_definition_organization_id ON public.flow_definition USING btree (organization_id);
CREATE INDEX ix_flow_node_execution_run_id ON public.flow_node_execution USING btree (flow_run_id);
CREATE INDEX ix_flow_run_organization_id ON public.flow_run USING btree (organization_id);
CREATE INDEX ix_flow_run_version_id ON public.flow_run USING btree (flow_version_id);
CREATE INDEX ix_flow_version_definition_id ON public.flow_definition_version USING btree (flow_definition_id);
CREATE INDEX ix_industrial_object_department_id ON public.industrial_object USING btree (department_id);
CREATE UNIQUE INDEX ix_industrial_object_org_type_code ON public.industrial_object USING btree (organization_id, object_type, code);
CREATE INDEX ix_industrial_object_organization_id ON public.industrial_object USING btree (organization_id);
CREATE INDEX ix_industrial_object_visible_departments ON public.industrial_object USING gin (visible_departments);
CREATE INDEX ix_job_lease_expires_at ON public.job USING btree (lease_expires_at);
CREATE INDEX ix_job_organization_id ON public.job USING btree (organization_id);
CREATE INDEX ix_job_run_after ON public.job USING btree (run_after);
CREATE INDEX ix_job_status ON public.job USING btree (status);
CREATE INDEX ix_model_organization_id ON public.model USING btree (organization_id);
CREATE INDEX ix_model_version_model_id ON public.model_version USING btree (model_id);
CREATE INDEX ix_outbox_event_pending ON public.outbox_event USING btree (delivered_at NULLS FIRST, occurred_at);
CREATE INDEX ix_parameter_candidate_parameter_id ON public.parameter_candidate USING btree (parameter_id);
CREATE INDEX ix_parameter_organization_id ON public.parameter USING btree (organization_id);
CREATE INDEX ix_parameter_version_parameter_id ON public.parameter_version USING btree (parameter_id);
CREATE INDEX ix_provenance_edge_derivation_run_id ON public.provenance_edge USING btree (derivation_run_id);
CREATE INDEX ix_provenance_edge_source ON public.provenance_edge USING btree (source_type, source_id);
CREATE INDEX ix_provenance_edge_target ON public.provenance_edge USING btree (target_type, target_id);
CREATE INDEX ix_recipe_version_recipe_id ON public.transformation_recipe_version USING btree (recipe_id);
CREATE INDEX ix_refresh_session_expires_at ON public.refresh_session USING btree (expires_at);
CREATE INDEX ix_refresh_session_family_id ON public.refresh_session USING btree (family_id);
CREATE INDEX ix_refresh_session_user_id_revoked_at ON public.refresh_session USING btree (user_id, revoked_at);
CREATE INDEX ix_secret_organization_id ON public.secret USING btree (organization_id);
CREATE INDEX ix_transformation_recipe_organization_id ON public.transformation_recipe USING btree (organization_id);
CREATE INDEX ix_user_department_department_id ON public.app_user_department USING btree (department_id);
CREATE INDEX ix_user_department_user_id ON public.app_user_department USING btree (user_id);
CREATE UNIQUE INDEX uq_showcase_conv_msg_block ON public.ai_showcase_item USING btree (conversation_id, source_message_id, source_block_index);
CREATE TRIGGER prevent_modify_audit_event BEFORE DELETE OR UPDATE ON public.audit_event FOR EACH ROW EXECUTE FUNCTION public.raise_immutable_violation();
CREATE TRIGGER prevent_modify_component_version BEFORE DELETE OR UPDATE ON public.component_version FOR EACH ROW EXECUTE FUNCTION public.raise_immutable_violation();
CREATE TRIGGER prevent_modify_evidence_set_version BEFORE DELETE OR UPDATE ON public.evidence_set_version FOR EACH ROW EXECUTE FUNCTION public.raise_immutable_violation();
CREATE TRIGGER prevent_modify_flow_version BEFORE DELETE OR UPDATE ON public.flow_definition_version FOR EACH ROW EXECUTE FUNCTION public.raise_immutable_violation();
ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_user(id);
ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.fact_data_index
    ADD CONSTRAINT fact_data_index_fact_id_fkey FOREIGN KEY (fact_id) REFERENCES public.fact(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ai_message
    ADD CONSTRAINT fk_ai_message_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.ai_conversation(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ai_showcase_item
    ADD CONSTRAINT fk_ai_showcase_item_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.ai_conversation(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.app_user_department
    ADD CONSTRAINT fk_app_user_department_department_id FOREIGN KEY (department_id) REFERENCES public.department(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.app_user_department
    ADD CONSTRAINT fk_app_user_department_user_id FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.artifact
    ADD CONSTRAINT fk_artifact_sha256 FOREIGN KEY (sha256) REFERENCES public.artifact_blob(sha256);
ALTER TABLE ONLY public.artifact
    ADD CONSTRAINT fk_artifact_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES public.app_user(id);
ALTER TABLE ONLY public.component
    ADD CONSTRAINT fk_component_active_version_id FOREIGN KEY (active_version_id) REFERENCES public.component_version(id);
ALTER TABLE ONLY public.component_version
    ADD CONSTRAINT fk_component_version_component_id FOREIGN KEY (component_id) REFERENCES public.component(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT fk_conv_participant_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.ai_conversation(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.conversation_participant
    ADD CONSTRAINT fk_conv_participant_user_id FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_parent_id FOREIGN KEY (parent_id) REFERENCES public.department(id);
ALTER TABLE ONLY public.derivation_run
    ADD CONSTRAINT fk_derivation_run_evidence_set_version_id FOREIGN KEY (evidence_set_version_id) REFERENCES public.evidence_set_version(id);
ALTER TABLE ONLY public.derivation_run
    ADD CONSTRAINT fk_derivation_run_job_id FOREIGN KEY (job_id) REFERENCES public.job(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.derivation_run
    ADD CONSTRAINT fk_derivation_run_recipe_version_id FOREIGN KEY (recipe_version_id) REFERENCES public.transformation_recipe_version(id);
ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT fk_equipment_department_id FOREIGN KEY (department_id) REFERENCES public.department(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.evidence_set_version
    ADD CONSTRAINT fk_evidence_set_version_evidence_set_id FOREIGN KEY (evidence_set_id) REFERENCES public.evidence_set(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fk_fact_created_by FOREIGN KEY (created_by) REFERENCES public.app_user(id);
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fk_fact_flow_run_id FOREIGN KEY (flow_run_id) REFERENCES public.flow_run(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fk_fact_object_id FOREIGN KEY (object_id) REFERENCES public.industrial_object(id);
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fk_fact_source_artifact_id FOREIGN KEY (source_artifact_id) REFERENCES public.artifact(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.flow_definition
    ADD CONSTRAINT fk_flow_definition_department FOREIGN KEY (department_id) REFERENCES public.department(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.flow_node_execution
    ADD CONSTRAINT fk_flow_node_execution_run_id FOREIGN KEY (flow_run_id) REFERENCES public.flow_run(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.flow_run
    ADD CONSTRAINT fk_flow_run_version_id FOREIGN KEY (flow_version_id) REFERENCES public.flow_definition_version(id);
ALTER TABLE ONLY public.flow_definition_version
    ADD CONSTRAINT fk_flow_version_definition_id FOREIGN KEY (flow_definition_id) REFERENCES public.flow_definition(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.job
    ADD CONSTRAINT fk_job_created_by FOREIGN KEY (created_by) REFERENCES public.app_user(id);
ALTER TABLE ONLY public.model_version
    ADD CONSTRAINT fk_model_version_model_id FOREIGN KEY (model_id) REFERENCES public.model(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.parameter_candidate
    ADD CONSTRAINT fk_parameter_candidate_derivation_run_id FOREIGN KEY (derivation_run_id) REFERENCES public.derivation_run(id);
ALTER TABLE ONLY public.parameter_candidate
    ADD CONSTRAINT fk_parameter_candidate_parameter_id FOREIGN KEY (parameter_id) REFERENCES public.parameter(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.parameter_version
    ADD CONSTRAINT fk_parameter_version_derivation_run_id FOREIGN KEY (derivation_run_id) REFERENCES public.derivation_run(id);
ALTER TABLE ONLY public.parameter_version
    ADD CONSTRAINT fk_parameter_version_parameter_id FOREIGN KEY (parameter_id) REFERENCES public.parameter(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.provenance_edge
    ADD CONSTRAINT fk_provenance_edge_derivation_run_id FOREIGN KEY (derivation_run_id) REFERENCES public.derivation_run(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.transformation_recipe_version
    ADD CONSTRAINT fk_recipe_version_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.transformation_recipe(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.refresh_session
    ADD CONSTRAINT fk_refresh_session_replaced_by FOREIGN KEY (replaced_by) REFERENCES public.refresh_session(id);
ALTER TABLE ONLY public.refresh_session
    ADD CONSTRAINT fk_refresh_session_user_id FOREIGN KEY (user_id) REFERENCES public.app_user(id);
ALTER TABLE ONLY public.industrial_object
    ADD CONSTRAINT industrial_object_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE SET NULL;
ALTER TABLE public.ai_conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artifact ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backup_record ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.department ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.derivation_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_set ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fact ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flow_definition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flow_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.industrial_object ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parameter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provenance_edge ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.secret ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ai_conversation USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.app_user USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.artifact USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.audit_event USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.backup_record USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.component USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.department USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.derivation_run USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.equipment USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.evidence_set USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.fact USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.flow_definition USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.flow_run USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.industrial_object USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.job USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.model USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.parameter USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.provenance_edge USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.secret USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
CREATE POLICY tenant_isolation ON public.transformation_recipe USING ((organization_id = (current_setting('app.current_org_id'::text, true))::uuid));
ALTER TABLE public.transformation_recipe ENABLE ROW LEVEL SECURITY;"""


# ---- Database role and grant DDL (not captured by pg_dump --no-privileges) ----

_ROLES_SQL = """
-- Create database roles (IF NOT EXISTS via DO block)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'irip_migrate') THEN
        CREATE ROLE irip_migrate LOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'irip_runtime') THEN
        CREATE ROLE irip_runtime LOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'irip_audit_writer') THEN
        CREATE ROLE irip_audit_writer NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'irip_app') THEN
        CREATE ROLE irip_app NOLOGIN;
    END IF;
END
$$;

-- irip_migrate: migration owner, full DDL/DML privileges
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO irip_migrate;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO irip_migrate;
GRANT USAGE, CREATE ON SCHEMA public TO irip_migrate;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO irip_migrate;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO irip_migrate;

-- irip_runtime: runtime role, minimal DML on business tables
GRANT USAGE ON SCHEMA public TO irip_runtime;


DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_config') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_config" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_conversation') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_conversation" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_message') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_message" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_showcase_item') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_showcase_item" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_tool') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_tool" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_user') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app_user" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_user_department') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app_user_department" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artifact') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "artifact" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artifact_blob') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "artifact_blob" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'audit_event') THEN
        GRANT SELECT, INSERT ON TABLE "audit_event" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'backup_record') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "backup_record" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'component') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "component" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'component_version') THEN
        GRANT SELECT, INSERT ON TABLE "component_version" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversation_participant') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "conversation_participant" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'department') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "department" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'derivation_run') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "derivation_run" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'equipment') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "equipment" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'evidence_set') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "evidence_set" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'evidence_set_version') THEN
        GRANT SELECT, INSERT ON TABLE "evidence_set_version" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'fact') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "fact" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'fact_data_index') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "fact_data_index" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_definition') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_definition" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_definition_version') THEN
        GRANT SELECT, INSERT ON TABLE "flow_definition_version" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_node_execution') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_node_execution" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_run') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_run" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'industrial_object') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "industrial_object" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'job') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "job" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'model') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "model" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'model_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "model_version" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'object_type_dict') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "object_type_dict" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'outbox_event') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "outbox_event" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter_candidate') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter_candidate" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter_version" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'provenance_edge') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "provenance_edge" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'refresh_session') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "refresh_session" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'role') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "role" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'secret') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "secret" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transformation_recipe') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "transformation_recipe" TO irip_runtime;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transformation_recipe_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "transformation_recipe_version" TO irip_runtime;
    END IF;
END $$;

-- irip_audit_writer: audit write only
GRANT USAGE ON SCHEMA public TO irip_audit_writer;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'audit_event') THEN
        GRANT INSERT ON TABLE "audit_event" TO irip_audit_writer;
    END IF;
END $$;

-- irip_app: legacy application role (from migration 0005)


DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_config') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_config" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_conversation') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_conversation" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_message') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_message" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_showcase_item') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_showcase_item" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ai_tool') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "ai_tool" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_user') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app_user" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'app_user_department') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "app_user_department" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artifact') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "artifact" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'artifact_blob') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "artifact_blob" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'audit_event') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "audit_event" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'component') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "component" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'component_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "component_version" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversation_participant') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "conversation_participant" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'department') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "department" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'derivation_run') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "derivation_run" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'equipment') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "equipment" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'evidence_set') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "evidence_set" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'evidence_set_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "evidence_set_version" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'fact') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "fact" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_definition') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_definition" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_definition_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_definition_version" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_node_execution') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_node_execution" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'flow_run') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "flow_run" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'industrial_object') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "industrial_object" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'job') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "job" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'model') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "model" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'model_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "model_version" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'object_type_dict') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "object_type_dict" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'outbox_event') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "outbox_event" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter_candidate') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter_candidate" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'parameter_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "parameter_version" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'provenance_edge') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "provenance_edge" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'refresh_session') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "refresh_session" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'role') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "role" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'secret') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "secret" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transformation_recipe') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "transformation_recipe" TO irip_app;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'transformation_recipe_version') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "transformation_recipe_version" TO irip_app;
    END IF;
END $$;

-- Default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO irip_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO irip_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO irip_runtime;
"""


def _split_sql(sql: str) -> list[str]:
    """Split a multi-statement SQL string into individual statements.

    Handles PostgreSQL dollar quoting ($$ ... $$ or $tag$ ... $tag$)
    to avoid splitting inside function/trigger definitions.

    Args:
        sql: Multi-statement SQL string.

    Returns:
        List of individual SQL statements.
    """
    statements: list[str] = []
    current: list[str] = []
    in_dollar_quote: bool = False
    dollar_tag: str = ""
    i: int = 0
    while i < len(sql):
        # Check for dollar quote start/end
        if not in_dollar_quote and sql[i] == "$":
            j: int = i + 1
            while j < len(sql) and (sql[j].isalnum() or sql[j] == "_"):
                j += 1
            if j < len(sql) and sql[j] == "$":
                tag: str = sql[i : j + 1]
                current.append(tag)
                in_dollar_quote = True
                dollar_tag = tag
                i = j + 1
                continue
        if in_dollar_quote and sql[i : i + len(dollar_tag)] == dollar_tag:
            current.append(dollar_tag)
            in_dollar_quote = False
            _tag_len: int = len(dollar_tag)
            dollar_tag = ""
            i += _tag_len
            continue
        if not in_dollar_quote and sql[i] == ";":
            stmt: str = "".join(current).strip()
            if stmt:
                statements.append(stmt)
            current = []
            i += 1
            continue
        current.append(sql[i])
        i += 1
    # Last statement (if no trailing semicolon)
    stmt = "".join(current).strip()
    if stmt:
        statements.append(stmt)
    return statements


def upgrade() -> None:
    """Create complete baseline schema (replaces migrations 0001-0061).

    1. Execute raw schema SQL (extensions, functions, tables, constraints,
       indexes, triggers, RLS policies) from pg_dump.
    2. Create database roles and grant privileges.
    """
    # ---- 1. Schema objects (tables, indexes, constraints, triggers, RLS) ----
    # psycopg3 async driver does not support multi-statement op.execute(),
    # so we split the schema SQL into individual statements.
    for _stmt in _split_sql(_SCHEMA_SQL):
        op.execute(_stmt)

    # ---- 2. Database roles and grants ----
    # Reset search_path to public (pg_dump sets it to '' which breaks GRANT)
    op.execute("SET search_path TO public")
    for _stmt in _split_sql(_ROLES_SQL):
        op.execute(_stmt)


def downgrade() -> None:
    """Drop all schema objects created by the baseline.

    Drops in reverse dependency order: policies, RLS, triggers, FKs, tables,
    functions, extensions, and roles.
    """
    # Drop all policies (safe to drop even if not exists)
    _rls_tables = [
        "ai_conversation", "app_user", "artifact", "audit_event", "backup_record",
        "component", "department", "derivation_run", "equipment", "evidence_set",
        "fact", "flow_definition", "flow_run", "industrial_object", "job",
        "model", "parameter", "provenance_edge", "secret", "transformation_recipe",
    ]
    for _table in _rls_tables:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_table}")

    # Disable and un-force RLS
    for _table in _rls_tables:
        op.execute(f"ALTER TABLE IF EXISTS {_table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE IF EXISTS {_table} DISABLE ROW LEVEL SECURITY")

    # Drop triggers
    _triggers = [
        ("prevent_modify_audit_event", "audit_event"),
        ("prevent_modify_component_version", "component_version"),
        ("prevent_modify_evidence_set_version", "evidence_set_version"),
        ("prevent_modify_flow_version", "flow_definition_version"),
    ]
    for _trigger, _table in _triggers:
        op.execute(f"DROP TRIGGER IF EXISTS {_trigger} ON {_table}")

    # Drop all tables (CASCADE handles FK dependencies)
    for _table in reversed(_ALL_TABLES):
        op.execute(f"DROP TABLE IF EXISTS {_table} CASCADE")

    # Drop function
    op.execute("DROP FUNCTION IF EXISTS raise_immutable_violation()")

    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    op.execute("DROP EXTENSION IF EXISTS citext")

    # Drop roles (revoke privileges first)
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM irip_app")
    op.execute("REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM irip_app")
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM irip_runtime")
    op.execute("REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM irip_runtime")
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM irip_migrate")
    op.execute("REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM irip_migrate")
    op.execute("REVOKE USAGE ON SCHEMA public FROM irip_runtime")
    op.execute("REVOKE USAGE, CREATE ON SCHEMA public FROM irip_migrate")
    op.execute("REVOKE USAGE ON SCHEMA public FROM irip_audit_writer")
    op.execute("DROP ROLE IF EXISTS irip_app")
    op.execute("DROP ROLE IF EXISTS irip_audit_writer")
    op.execute("DROP ROLE IF EXISTS irip_runtime")
    op.execute("DROP ROLE IF EXISTS irip_migrate")
